export const GET_CART_PROCESS = "GET_CART_PROCESS";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS ";
export const GET_CART_FAILED = "GET_CART_FAILED";

export const ADD_CART_PROCESS = "ADD_CART_PROCESS";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS ";
export const ADD_CART_FAILED = "ADD_CART_FAILED";

export const UPDATE_CART_PROCESS = "UPDATE_CART_PROCESS";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS ";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED ";

export const DELETE_CART_PROCESS = "DELETE_CART_PROCESS";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS ";
export const DELETE_CART_FAILED = "DELETE_CART_FAILED";

export const RESET_STATUS = "RESET_STATUS";
