// Adding product to cart
export const GET_PRODUCT_PROCESS = "GET_PRODUCT_PROCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS ";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const PRODUCT_DETAIL_PROCESS = "PRODUCT_DETAIL_PROCESS";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS ";
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILED";

export const STORE_PRODUCT_PROCESS = "STORE_PRODUCT_PROCESS";
export const STORE_PRODUCT_SUCCESS = "STORE_PRODUCT_SUCCESS ";
export const STORE_PRODUCT_FAILED = "STORE_PRODUCT_FAILED";

export const PRODUCT_BY_CAT_PROCESS = "PRODUCT_BY_CAT_PROCESS";
export const PRODUCT_BY_CAT_SUCCESS = "PRODUCT_BY_CAT_SUCCESS ";
export const PRODUCT_BY_CAT_FAILED = "PRODUCT_BY_CAT_FAILED ";

export const RESET = "RESET";
